spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    url: jdbc:h2:mem:testdb;MVCC=TRUE

    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    root : info
    com.utti.jpashop : debug
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
